name: weddingbook
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ">=3.4.3 <4.0.0"

dependencies:
    auto_size_text: ^3.0.0
    equatable: ^2.0.7
    ferry: ^0.16.1+2
    flutter:
        sdk: flutter
    flutter_bloc: ^9.1.0
    flutter_staggered_grid_view: ^0.7.0
    google_fonts: ^6.2.1
    gql_exec: ^1.0.0+1
    gql_http_link: ^1.1.0
    iconsax_flutter: ^1.0.0
    keyboard_avoider: ^0.2.0
    lottie: ^3.3.1
    smooth_page_indicator: ^1.2.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.0
    ferry_generator: ^0.12.0+2
    build_runner: ^2.4.15

flutter:
    uses-material-design: true
    assets:
        - assets/lotties/
        - assets/fonts/
        - assets/images/
    fonts:
        - family: PlayfairDisplay
          fonts:
              - asset: assets/fonts/PlayfairDisplayRegular.ttf
              - asset: assets/fonts/PlayfairDisplaySemibold.ttf
                weight: 600
              - asset: assets/fonts/PlayfairDisplayBold.ttf
                weight: 700
              - asset: assets/fonts/PlayfairDisplayExtrabold.ttf
                weight: 800
              - asset: assets/fonts/PlayfairDisplayBlack.ttf
                weight: 900
